### ISSUE TITLE
Support opening files with "text/x-..." MIME type as text

### ISSUE THREAD

**Issue by HighCommander4** [Rob--W/open-in-browser#1]
As mentioned [here](https://github.com/spasche/openinbrowser/issues/23#issuecomment-331664001), this is one of the missing pieces of functionality compared to [@est31's version](https://github.com/est31/openinbrowser/). It would be great to have this added :)

**Comment by est31** [comment]
The way I did it was creating a whitelist of text/... MIME types that firefox recognizes and then treating all other MIME types as foreign... its a bit risky though.

**Comment by est31** [comment]
Optimally, we could integrate the UI into the already existing dialog, then we wouldn't have to duplicate all the logic: https://bugzilla.mozilla.org/show_bug.cgi?id=1344648

**Comment by Rob--W** [comment]
> The way I did it was creating a whitelist of text/...  MIME types that firefox recognizes and then treating all other MIME  types as foreign... its a bit risky though.

What I'm doing is reading through Firefox's source code to understand when Firefox decides to show the dialog, and try to replicate that.
The logic is quite complicated, and it is likely that for some types I will display a dialog even though the current action is to not show a dialog. However, the user can permanently save a choice so that the dialog won't appear again.

It seems that [`nsDocumentOpenInfo::OnStartRequest`](https://searchfox.org/mozilla-central/rev/56ad02e34d0d36ca4d5ccaa885d26aff270b8ff7/uriloader/base/nsURILoader.cpp#201) is the entry point, and [`nsDocumentOpenInfo::DispatchContent`](https://searchfox.org/mozilla-central/rev/56ad02e34d0d36ca4d5ccaa885d26aff270b8ff7/uriloader/base/nsURILoader.cpp#367) is first callee that makes decisions on whether to open the dialog or not.

Before looking through the above code, I already found a list of some common types by [searching for `"Gecko-Content-Viewers"`](https://searchfox.org/mozilla-central/search?q=%22Gecko-Content-Viewers%22&case=false&regexp=false&path=):
- https://searchfox.org/mozilla-central/rev/56ad02e34d0d36ca4d5ccaa885d26aff270b8ff7/layout/build/nsContentDLF.h#68-100
- https://searchfox.org/mozilla-central/rev/56ad02e34d0d36ca4d5ccaa885d26aff270b8ff7/image/build/nsImageModule.cpp#73-85
- https://searchfox.org/mozilla-central/rev/56ad02e34d0d36ca4d5ccaa885d26aff270b8ff7/xpfe/components/build/nsModule.cpp#33

( the constants are defined in https://searchfox.org/mozilla-central/rev/56ad02e34d0d36ca4d5ccaa885d26aff270b8ff7/netwerk/mime/nsMimeTypes.h )

> Optimally, we could integrate the UI into the already existing dialog, then we wouldn't have to duplicate all the logic: https://bugzilla.mozilla.org/show_bug.cgi?id=1344648

That would be ideal, but not feasible for Firefox 57.

**Comment by Rob--W** [comment]
Some update: Last month I spent two weeks on learning and documenting the intrinsics of Firefox's content handling logic and implemented it so that the extension behaved identical to Firefox in terms of content handling. Unfortunately, right after I finished but before I pushed the changes my laptops were stolen, and I don't have the time nor motivation to redo this work at this time.

I will try to update the MIME lists to match Firefox's because that is the common case.

In case anyone wants to contribute to a content sniffer, I posted a guide for the implementation at #5. The logic is non-trivial, so please include some tests and make sure that these pass.

**Comment by est31** [comment]
@Rob--W that sounds horrible! Hope you are doing well :heart: :)
