### ISSUE TITLE
Saving file requires extra click

### ISSUE THREAD

**Issue by ThiefMaster** [Rob--W/open-in-browser#25]
With the extension enabled I seem to have to go through two dialogs to save a file to disk. I just went to download Chrome so I have it installed as well, and the first dialog was the one from the extension that has the "open in browser" option; after clicking "save to disk" I got yet another download dialog (this time the normal one from firefox).

**Comment by Rob--W** [comment]
Due to technical limitations, it is not possible to automatically avoid this dialog.
I found a work-around to skip the dialog anyway, and added a new option and instructions at the Preference page to enable this.

Install version 2.4 of Open in Browser, and let me know if the instructions at the options page are clear enough and effective.

**Comment by ThiefMaster** [comment]
Works fine. Might be a good idea to ask the Firefox devs for a better solution in the Webextension API. Currently a site could specify "your" MIME type to trigger a download prompt immediately, which isn't a big deal but not very nice either.

Also - not sure if it's related - when clicking a download link another dialog pops open for the fraction of a second before the download dialog of your extension takes over.

PS: I just noticed that finally this extension works for downloads from POST requests. I always missed that in the legacy version. Very nice that this is finally possible!

**Comment by Rob--W** [comment]
> Currently a site could specify "your" MIME type to trigger a download prompt immediately, which isn't a big deal but not very nice either.

I considered supporting a custom string instead of a checkbox, but decided against because it would be more complicated for a user, while the impact would be low.

In a default installation, files are saved to a download directory without confirmation. My custom MIME would not change this behavior.

If the "Ask where to save downloads" browser preference is enabled, a Save As dialog appears. With my custom MIME, the worst that can happen is that the file is automatically saved to disk without user confirmation. That in itself is annoying but has no severe consequences.

To limit the impact I can consider detecting this custom MIME and forcing it to "application/octet-stream". But for now I won't implement it until I see a good reason to disallow this special MIME.

> Also - not sure if it's related - when clicking a download link another dialog pops open for the fraction of a second before the download dialog of your extension takes over.

In the case of Chrome? That is not specific to my extension. I think that they first open a popup window before requesting the download URL.

**Comment by ThiefMaster** [comment]
I tested it with the [VLC download link](http://mirror.switch.ch/ftp/mirror/videolan/vlc/2.2.6/win32/vlc-2.2.6-win32.exe); opening the link directly in a fresh tab, so nothing opening a popup or anything. I'll see if i can record my screen to show it.

**Comment by ThiefMaster** [comment]
I get this dialog (the title becomes `moz-extension://23c...` a moment later):

![image](https://user-images.githubusercontent.com/179599/33215070-b6ba7b2a-d12e-11e7-86f4-2994f94cab75.png)

then it goes away and the proper dialog shows up:

![image](https://user-images.githubusercontent.com/179599/33215185-13925c78-d12f-11e7-9768-ab1718632c47.png)

Maybe it is actually the same dialog that gets moved to the center of the screen?

**Comment by Rob--W** [comment]
> Maybe it is actually the same dialog that gets moved to the center of the screen?

Likely. But I expected the window to already be centered when opened, so I am surprised that it opened at the top of the screen instead of at the center of the screen. Maybe some Windows-specific behavior?
