### ISSUE TITLE
Download dialog shown for non-download

### ISSUE THREAD

**Issue by Lekensteyn** [Rob--W/open-in-browser#31]
Visiting https://www.golang-book.com/books/intro/9 results in a download dialog. Likely has something to do with the `text-html` Content Type:
```
HTTP/1.1 200 OK
Date: Sun, 24 Dec 2017 23:58:07 GMT
Content-Type: text-html; charset=utf-8
Content-Length: 9880
Connection: keep-alive
Set-Cookie: __cfduid=d3ed6b67dda06cf2bd668179f4dd8eae01514159887; expires=Mon, 24-Dec-18 23:58:07 GMT; path=/; domain=.golang-book.com; HttpOnly
X-Cloud-Trace-Context: 2e23b615a0de191451aeb86f5b293c93;o=1
Server: cloudflare
CF-RAY: 3d2781bf8b472c3c-AMS
```

Expected behavior:
show page as normal.

**Comment by Rob--W** [comment]
Currently it shows `text/html`, so it has been fixed.

The MIME detection of the extension works, Firefox also considers the MIME type to be empty:
`Services.netUtils.parseResponseContentType("text-html; charset=utf-8", {}, {}) === ""`

The reason that Firefox still displays the content inline is because "text-html" is treated as an empty string, and that triggers content sniffing. The response looks like HTML, so Firefox displays the content inline instead of showing a dialog.

If you don't want to see the dialog, use "Open in browser as [server-sent MIME]" option in the dialog and remember the choice. If you ever want to force the dialog to be shown, use the Open in Browser option in the Tools menu, or go to the extension's preference page and forget about the saved choice.

**Comment by Lekensteyn** [comment]
I contacted the author and they fixed their headers. The current dialog shows an empty MIME type, is it an idea to treat the response as normal rather than as download? Or would that break known other cases?
