### ISSUE TITLE
Feature Request: Select "Open With" Application

### ISSUE THREAD

**Issue by adamsmd** [Rob--W/open-in-browser#64]
In the standard download dialog box, the "Open with" option has a drop-down that lets me choose which application to use to open the file.  However, in the "Open in Browser" dialog box, the "Open with" option shows only "Firefox (Choose other Application)", which if selected opens the standard download dialog box.

This means that I have to go through two dialogs if I just want to open a file (e.g., a Word Document) with an application.

Would there be some way to add that drop-down list to the "Open in Browser" dialog, so I don't have to go through dialogs and instead could select the application and open in that application directly from the "Open in Browser" dialog?

(Note, this is on Ubuntu 19.04, Firefox 70.0.1, and Open in Browser 2.9.)

**Comment by Rob--W** [comment]
There is no extension API that allows me to implement the feature that you're requesting: It is not possible to retrieve the list of applications that handles a file, let alone launch an arbitrary program with that information.

Currently, the only way to implement this feature is to develop a native application and ask users to install it. This native application would then be used to look up supported applications. I'm probably not going to implement this, because it takes too much efforts to implement this (securely) and maintain it (with separate implementations for the three desktop operating systems).

**Comment by adamsmd** [comment]
I had not thought about that aspect, but what you say makes sense.  Closing the PR as not piratically to be implementable.
