### ISSUE TITLE
Downthemall and Turbo Download Manager integration

### ISSUE THREAD

**Issue by regs01** [Rob--W/open-in-browser#69]
Is it possible to make an option to download with Downthemall and Turbo Download Manager?

**Comment by Rob--W** [comment]
This is similar to the feature request at #54. The same holds: it would only work for some kinds of downloads.

Those other add-ons cannot see the download instruction from my extensions, so it wouldn't easily be possible, unless those download managers provide an API for other extensions to use. I am not interested in reviving the functionality that I added before (mentioned in #54) and integrate with those other add-ons, because the solution would only work for some cases, and I also have a lack of time to do so.
