### ISSUE TITLE
Colour of url-remainder text should not use ButtonShadow

### ISSUE THREAD

**Issue by davidf-woaf-net** [Rob--W/open-in-browser#8]
There is no guarantee that ButtonShadow offers sufficient contrast for readable text against the background of ButtonFace.

```diff
diff --git a/extension/dialog.css b/extension/dialog.css
index b8f62e6..a3b4023 100644
--- a/extension/dialog.css
+++ b/extension/dialog.css
@@ -95,7 +95,7 @@ body {
 }
 #url-protocol,
 #url-remainder {
-    color: ButtonShadow;
+    color: ButtonText;
 }
```

**Comment by Rob--W** [comment]
The text is intentionally faded to ensure that the domain of the URL stands out. Upon hover, the URL is clearly shown, with a clear contrast.

If I change the color from ButtonShadow to ButtonText, then the domain does not stand out any more.
Instead of changing the color, I can also use opacity to decrease the visual prominence of the non-domain parts of the URL. Does that look like a good solution to your issue?

**Comment by davidf-woaf-net** [comment]
That would be worth a try.  Try using ButtonText with opacity 0.6.  For instance, https://jsfiddle.net/8cctjv4n/
